#!/usr/bin/env bash

# File:        mkpw
# Author:      Sven Mäder <maeder@phys.ethz.ch>, ETH Zurich, ISG D-PHYS
# Date:        2024-08-29
# Github:      https://github.com/rda0/mkpw/blob/master/mkpw.sh
#
# Description: Generates random secure passwords suitable for linux logins,
#              prints out the creatext password and the corresponding hash.
#              Alternatively hashes input password.
#
# Requirement: `mkpasswd`, provided by the package whois, on debian based
#              distributions run the following command to install it:
#
#              apt install whois
#
# Copyright 2024 Sven Mäder
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

## hash algorithm variables

# character sets to use for passwords
# escaping: '\\' --> '\', '\-' --> '-'
charset_g='[:graph:]'
charset_a='[:alnum:]'
charset_p='[:print:]'
charset_c='\-#,./:=?@[]^{}~a-zA-Z0-9'
charset_d='\\\-`_~!@#$%^&*()+={}[]|;:"<>,.?/a-zA-Z0-9'\'
charset_q='\\\-_~!@#$%^&*()+={}[]|;:<>,.?/a-zA-Z0-9'
# default charset
passwd_charset=${charset_g}
# character set to use for salts (allowed charset = ./a-zA-Z0-9 )
salt_charset='./a-zA-Z0-9'
# minimum password length not showing insecure warning
passwd_min=12
# default password length
passwd_len=32
# default rounds (-1 == use defaults)
rounds=-1
# default salt_len (-1 == use defaults)
salt_len=-1
# possible hashing algorithms
methods='yescrypt gost-yescrypt scrypt bcrypt bcrypt-a sha512crypt sha256crypt sunmd5 md5crypt bsdicrypt descrypt nt'
# default method
method='yescrypt'
# hash input (provide existing password to hash)
hash_input=0
hash_input_stdin=0

## loop variables
# loop counter
counter=0
# default number of passwords to generate
amount=1

print_usage() {
  echo -e "Usage: ${0} [options] [length [amount]]"
  echo -e "\n    Generates strong passwords suitable for linux logins."
  echo -e "\nOutput: <cleartext-password>   <hashed-password>"
  echo -e "\nOptions:\n"
  echo "    length"
  echo "        Password length (default=32)"
  echo "    amount"
  echo "        Amount of passwords generated (default=1)"
  echo "    -g, --graph"
  echo "        Use printable characters only (default)"
  echo "    -a, --alnum"
  echo "        Use alphanumeric characters only"
  echo "    -p, --print"
  echo "        Use printable characters including space"
  echo "    -c, --custom"
  echo "        Use custom character set (ETH Zurich): $(echo -n ${charset_c} | sed 's/\\-/-/' | sed 's/\\\\/\\/')"
  echo "    -d, --default"
  echo "        Use default character set: $(echo -n ${charset_d} | sed 's/\\-/-/' | sed 's/\\\\/\\/')"
  echo "    -q, --no-quotes"
  echo "        Use default character set: $(echo -n ${charset_q} | sed 's/\\-/-/' | sed 's/\\\\/\\/')"
  echo "    -h, --help"
  echo "        Print this help message"
  echo "    -m, --method TYPE"
  echo "        Compute the password using the TYPE method."
  echo "        Possible values for TYPE:"
  echo "        yescrypt        Yescrypt  (default)"
  echo "        gost-yescrypt   GOST Yescrypt"
  echo "        scrypt          scrypt"
  echo "        bcrypt          bcrypt"
  echo '        bcrypt-a        bcrypt (obsolete $2a$ version)'
  echo "        sha512crypt     SHA-512"
  echo "        sha256crypt     SHA-256"
  echo "        sunmd5          SunMD5"
  echo "        md5crypt        MD5"
  echo "        bsdicrypt       BSDI extended DES-based crypt(3)"
  echo "        descrypt        standard 56 bit DES-based crypt(3)"
  echo "        nt              NT-Hash"
  echo "    -r, --rounds ROUNDS"
  echo "        Compute the password using ROUNDS number of rounds (otherwise use default)."
  echo "    -i, --hash-input"
  echo "        Hash input password."
  echo "    -s, --stdin"
  echo "        Read input password from stdin (only with -i)."
}

check_opt() {
    if [ "${opt}" -eq 1 ]; then
        echo -e "error: Invalid combination of options\n" >&2
        print_usage
        exit 1
    fi
}

check_num() {
    re='^[0-9]+$'
    if ! [[ ${1} =~ $re ]] ; then
        echo -e "error: Wrong option or not a number\n" >&2
        print_usage
        exit 1
    fi
}

print_requirement() {
  echo -e "error: mkpasswd is not installed. To install run:"
  echo -e "\n    apt install whois\n"
}

print_passwd_insecure() {
  echo -e "warning: Using a too short password is insecure (recommended length: >= 16)\n"
}

print_passwd_too_long() {
  echo -e "error: Password is too long (maximum length = ${passwd_max})"
}

if [ "$(which mkpasswd)" != "/usr/bin/mkpasswd" ]; then
  print_requirement
  exit 1
fi

if [ "$#" -lt 0 ] || [ "$#" -gt 9 ]; then
  print_usage
  exit 1
fi

opt=0
num=0

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -h|--help)
        print_usage
        exit 0
        ;;
    -g|--graph)
        check_opt
        passwd_charset=${charset_g}
        opt=1
        ;;
    -a|--alnum)
        check_opt
        passwd_charset=${charset_a}
        opt=1
        ;;
    -p|--print)
        check_opt
        passwd_charset=${charset_p}
        opt=1
        ;;
    -c|--custom)
        check_opt
        passwd_charset=${charset_c}
        opt=1
        ;;
    -d|--default)
        check_opt
        passwd_charset=${charset_d}
        opt=1
        ;;
    -q|--no-quotes)
        check_opt
        passwd_charset=${charset_q}
        opt=1
        ;;
    -m|--method)
        valid_method=0
        for i in ${methods};
        do
            if [ "${i}" == "${2}" ]; then
                valid_method=1
            fi
        done
        if [ "${valid_method}" -eq 1 ]; then
            method=${2}
            shift
        else
            echo -e "Error: Invalid method\n" >&2
            print_usage
            exit 1
        fi
        ;;
    -r|--rounds)
        valid_rounds='[0-9]'
        if [[ ${2} =~ ${valid_rounds} ]] && [ ${2} -ge 0 ] && [ ${2} -le 999999999 ]; then
            rounds=${2}
            shift
        else
            echo -e "Error: Invalid value for rounds\n" >&2
            echo -e "Provide a numeric value between 0 and 999999999\n" >&2
            print_usage
            exit 1
        fi
        ;;
    -i|--hash-input)
        hash_input=1
        ;;
    -s|--stdin)
        hash_input_stdin=1
        ;;
    *)
        if [ ${num} -ge 2 ]; then
            echo -e "Error: Too many arguments\n" >&2
            print_usage
            exit 1
        fi
        check_num ${1}
        if [ ${num} -eq 0 ]; then
            passwd_len="${1}"
        fi
        if [ ${num} -eq 1 ]; then
            amount="${1}"
        fi
        ((num++))
        ;;
esac
shift # past argument or value
done

# defaults for algorithms
case ${method} in
    # for possible salt lengths see man crypt(5)
    yescrypt)
        # debian default rounds: 5
        if [ "${rounds}" == "-1" ]; then
            rounds=7
        fi
        ;;
    sha512crypt)
        salt_len=16
        if [ "${rounds}" == "-1" ]; then
            # debian default rounds: 5000
            rounds=500000
        fi
        ;;
    sha256crypt)
        salt_len=16
        if [ "${rounds}" == "-1" ]; then
            rounds=500000
        fi
        ;;
    md5crypt)
        salt_len=8
        rounds=-1
        ;;
    descrypt)
        salt_len=2
        passwd_max=8
        rounds=-1
        ;;
esac

# default uses no --rounds param and defaults of mkpasswd
rounds_param=""

if [ "${rounds}" != "-1" ]; then
    rounds_param="--rounds=${rounds}"
fi

# default uses no --salt param and defaults of mkpasswd
salt_param=""

if [ "${passwd_len}" -lt "${passwd_min}" ]; then
    print_passwd_insecure
fi

if [ ! -z "${passwd_max}" ] && [ "${passwd_len}" -gt "${passwd_max}" ]; then
    print_passwd_too_long
    exit 1
fi

while [ $counter -lt $amount ]; do
    if [ "${salt_len}" != "-1" ]; then
        salt=$(head -c"${salt_len}" < <(LC_CTYPE=C tr -dc "${salt_charset}" < /dev/urandom))
        salt_param="--salt=${salt}"
    fi

    if [ "${hash_input}" -eq 0 ]; then
        # generate random password
        passwd=$(head -c"${passwd_len}" < <(LC_CTYPE=C tr -dc "${passwd_charset}" < /dev/urandom))
        echo -n "${passwd}"
        echo -n '   '
        if [ "${rounds_param}" != "" ] && [ "${salt_param}" != "" ]; then
            echo -n "${passwd}" | /usr/bin/mkpasswd -s -m "${method}" "${rounds_param}" "${salt_param}"
        elif [ "${rounds_param}" != "" ]; then
            echo -n "${passwd}" | /usr/bin/mkpasswd -s -m "${method}" "${rounds_param}"
        elif [ "${salt_param}" != "" ]; then
            echo -n "${passwd}" | /usr/bin/mkpasswd -s -m "${method}" "${salt_param}"
        else
            echo -n "${passwd}" | /usr/bin/mkpasswd -s -m "${method}"
        fi
    else
        amount=1
        if [ "${hash_input_stdin}" -eq 1 ]; then
            # hash password from stdin
            passwd=$(cat)
            if [ "${rounds_param}" != "" ] && [ "${salt_param}" != "" ]; then
                echo -n "${passwd}" | /usr/bin/mkpasswd -s -m "${method}" "${rounds_param}" "${salt_param}"
            elif [ "${rounds_param}" != "" ]; then
                echo -n "${passwd}" | /usr/bin/mkpasswd -s -m "${method}" "${rounds_param}"
            elif [ "${salt_param}" != "" ]; then
                echo -n "${passwd}" | /usr/bin/mkpasswd -s -m "${method}" "${salt_param}"
            else
                echo -n "${passwd}" | /usr/bin/mkpasswd -s -m "${method}"
            fi
        else
            # hash password from user input
            if [ "${rounds_param}" != "" ] && [ "${salt_param}" != "" ]; then
                /usr/bin/mkpasswd -m "${method}" "${rounds_param}" "${salt_param}"
            elif [ "${rounds_param}" != "" ]; then
                /usr/bin/mkpasswd -m "${method}" "${rounds_param}"
            elif [ "${salt_param}" != "" ]; then
                /usr/bin/mkpasswd -m "${method}" "${salt_param}"
            else
                /usr/bin/mkpasswd -m "${method}"
            fi
        fi
    fi

    let counter+=1
done
